### ISSUE TITLE
Cannot find name 'test' and 'expected' in test

### ISSUE THREAD

**Issue by Belencha** [softwarecrafters-io/ts-eslint-prettier-jest#19]
Found when opening the project with vscode v1.88.1 in WSL2. After installing the project some warnings appear such:

```
Cannot find name 'test'. Do you need to install type definitions for a test runner? Try `npm i --save-dev @types/jest` or `npm i --save-dev @types/mocha`.ts(2582)

Cannot find name 'expect'. Did you mean 'expected'?ts(2552)
```

![image](https://github.com/softwarecrafters-io/ts-eslint-prettier-jest/assets/6985234/f40e896d-bace-46ce-8c89-bb883b3f696c)

**Comment by softwarecrafters-io** [comment]
It is already fixed. Thanks for letting me know.
